spring:
  config:
    activate:
      on-profile: test
  data:
    redis:
      host: localhost
      port: 6379
    mongodb:
      host: localhost
      port: 0
      database: test
  
  mongodb:
    embedded:
      version: 5.0.14

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 5.0.14


jwt:
  key: thisisadummykeyforciandtestenvironmentsonlydontuseinprod
  access:
    expiration: 3600000
  refresh:
    expiration: 604800000
