spring:
  config:
    activate:
      on-profile: test
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: dummy-client-id
            client-secret: dummy-client-secret
  data:
    redis:
      host: localhost
      port: 6379
    mongodb:
      host: localhost
      port: 0
      database: test
  
  mongodb:
    embedded:
      version: 4.4.26

  mail:
    host: localhost
    port: 1025
    username: test
    password: test
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 4.4.26


jwt:
  key: thisisadummykeyforciandtestenvironmentsonlydontuseinprod
  access:
    expiration: 3600000
  refresh:
    expiration: 604800000

app:
  auth:
    redirect-url: http://localhost:8080/test-callback
    allowed-email-domain: gachon.ac.kr

email:
  from: test@gachon.ac.kr
